// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    { type: "autogenerated", dirName: "." },
    {
      type: "link",
      label: "DSA Problems",
      href: "/dsa-problems",
    },
    {
      type: "link",
      label: "DSA Solutions",
      href: "/dsa-solutions",
    },
  ],
};

export default sidebars;
